/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentación;

import Modelo.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Isabella
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
       setLocationRelativeTo(null);
       mostrar();
    }
    
      public void mostrar() {
           
        Conexion con= new Conexion();
        Connection conexion= con.getConexion();
        
           
           String sql="select c.idconsulta,  c.fecha, c.hora, c.idcita, d.PrimerNombre,p.PrimerNombre,t.Nombre,s.nombre ,ci.`idConsultorio`\n" +
"from consulta c\n" +
"inner join cita ci\n" +
"on c.idcita= ci.idcita\n" +
"inner join doctor d\n" +
"on ci.idDoctor= d.idDoctor\n" +
"inner join paciente p\n" +
"on ci.idPaciente= p.idPaciente \n" +
" inner join tratamiento t\n" +
" on ci.idtratamiento= t.idtratamiento\n" +
" inner join servicio s\n" +
" on ci.idservicio= s.idservicio ";
           Statement st;
           
           DefaultTableModel model= new DefaultTableModel ();
           model.addColumn("NºConsulta");
           model.addColumn("Fecha");
           model.addColumn("Hora");
           model.addColumn("Nº Cita");
           model.addColumn("Doctor");
           model.addColumn("Paciente");
           model.addColumn("Tratamiento");
           model.addColumn("Servicio");
           model.addColumn("Nº Consultorio");
          
           
           TablaConsultas.setModel(model);
          
           
           String[] datos = new String[8];
           
            ResultSet rs;
            
            
        try {
            st= (Statement)conexion.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()){
              
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                
                
                 
                model.addRow(datos);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Doctores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Consultas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaConsultas = new javax.swing.JTable();
        buscarC = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Panel_Consultas.setBackground(new java.awt.Color(255, 255, 204));
        Panel_Consultas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Consultas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 1, 18))); // NOI18N
        Panel_Consultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Consultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaConsultas.setAutoCreateRowSorter(true);
        TablaConsultas.setBackground(new java.awt.Color(0, 255, 102));
        TablaConsultas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TablaConsultas.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        TablaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Consultorio", "Fecha", "Hora", "Doctor", "Paciente", "Subtotal", "Descuento", "Total"
            }
        ));
        TablaConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaConsultas.setFocusable(false);
        TablaConsultas.setGridColor(new java.awt.Color(51, 51, 51));
        TablaConsultas.setSelectionBackground(new java.awt.Color(0, 255, 255));
        TablaConsultas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(TablaConsultas);

        Panel_Consultas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 1060, 530));

        buscarC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscarC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarCKeyPressed(evt);
            }
        });
        Panel_Consultas.add(buscarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 350, 30));

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/cash.png"))); // NOI18N
        jButton2.setText("Generar Factura");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Panel_Consultas.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 590, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/search.png"))); // NOI18N
        Panel_Consultas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 40, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/refresh.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        Panel_Consultas.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1405, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Panel_Consultas, javax.swing.GroupLayout.PREFERRED_SIZE, 1395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Panel_Consultas, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
       new Factura().setVisible(true);
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buscarCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarCKeyPressed
        // TODO add your handling code here:
        
            Conexion con= new Conexion();
        Connection conexion= con.getConexion();
        
        
        
          String sql=" select c.fecha, c.hora, c.idcita, d.PrimerNombre,p.PrimerNombre,t.Nombre,s.nombre ,ci.`idConsultorio`\n" +
"from consulta WHERE d.PrimerNombre LIKE '%"+buscarC.getText()+"%' c\n" +
 "OR c.fecha LIKE '%"+buscarC.getText()+"%'"+
"inner join cita ci\n" +
"on c.idcita= ci.idcita\n" +
"inner join doctor d\n" +
"on ci.idDoctor= d.idDoctor\n" +
"inner join paciente p\n" +
"on ci.idPaciente= p.idPaciente \n" +
" inner join tratamiento t\n" +
" on ci.idtratamiento= t.idtratamiento\n" +
" inner join servicio s\n" +
" on ci.idservicio= s.idservicio";
        
  DefaultTableModel model= new DefaultTableModel ();
           model.addColumn("Fecha");
           model.addColumn("Hora");
           model.addColumn("Nº Cita");
           model.addColumn("Doctor");
           model.addColumn("Paciente");
           model.addColumn("Tratamiento");
           model.addColumn("Servicio");
           model.addColumn("Nº Consultorio");
            TablaConsultas.setModel(model);
            String[] datos = new String[7];
            
          try {
            

            Statement st;
                st = (Statement) conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            
             while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
               
                model.addRow(datos);
                 conexion.close();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Doctores.class.getName()).log(Level.SEVERE, null, ex);
            
        }
         
        
        
        
    }//GEN-LAST:event_buscarCKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Consultas;
    public javax.swing.JTable TablaConsultas;
    private javax.swing.JTextField buscarC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
