/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentación;


//import Modelo.Consultorio;
import Modelo.Usuario;
import Presentación.CitasP;
import Presentación.DoctoresP;
import Presentación.Login;
import Presentación.MenuDoctor;
import Presentación.PacientesP;
import Presentación.Servicios;
import Presentación.Tratamientos;
import java.awt.Desktop;
import java.net.URI;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Isabella
 */
public class Principal extends javax.swing.JFrame {
    
    Usuario mod;
//    Consultorio mod1;
    
   

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        
 
//        this.lblConsultorio.setText(fecha);
        
         this.setExtendedState(MAXIMIZED_BOTH);
       
    }
    
     public Principal(Usuario mod)
         {
             initComponents();
             setLocationRelativeTo(null);
             this.mod = mod;
             
             Calendar cal = Calendar.getInstance();
    String fecha, hora;
    fecha = cal.get(Calendar.DATE)+"/"+cal.get(Calendar.MONTH)+"/"+cal.get(Calendar.YEAR);
    hora = cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+":"+cal.get(Calendar.SECOND);
             lblUser.setText(mod.getUsuario());
             lblFecha.setText(fecha);
             lblHora.setText(hora);
             
             
        
             
             if(mod.getIdtipousuario() == 1)
             {
                 
             }else if(mod.getIdtipousuario() == 2)
             {
                 new MenuDoctor().setVisible(true);
                 new Principal().setVisible(false);
             }
         }
     
//     public Principal(Consultorio mod1)
//         {
//             initComponents();
//             setLocationRelativeTo(null);
//             this.mod1 = mod1;
//
//             
//             
//        lblNombreConsul.setText(mod1.getNombreConsultorio());
//             
////             if(mod.getIdtipousuario() == 1)
////             {
////                 
////             }else if(mod.getIdtipousuario() == 2)
////             {
////                 new MenuDoctor().setVisible(true);
////                 new Principal().setVisible(false);
////             }
//         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        btnDoctores = new javax.swing.JButton();
        btnTratamientos = new javax.swing.JButton();
        salirPr = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        btnPacientes1 = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnTratamientos2 = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        btnConsultas2 = new javax.swing.JButton();
        btnFacebook = new javax.swing.JButton();
        btnInstagram = new javax.swing.JButton();
        lblNombreConsul = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu_Principal");

        PanelPrincipal.setBackground(new java.awt.Color(0, 102, 153));
        PanelPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(132, 178, 60), null, null));

        btnDoctores.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnDoctores.setForeground(new java.awt.Color(255, 255, 255));
        btnDoctores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/doctor1.png"))); // NOI18N
        btnDoctores.setText(" Doctores");
        btnDoctores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDoctores.setBorderPainted(false);
        btnDoctores.setContentAreaFilled(false);
        btnDoctores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDoctores.setVerifyInputWhenFocusTarget(false);
        btnDoctores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctoresActionPerformed(evt);
            }
        });

        btnTratamientos.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        btnTratamientos.setForeground(new java.awt.Color(255, 255, 255));
        btnTratamientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/braces.png"))); // NOI18N
        btnTratamientos.setText(" Tratamientos");
        btnTratamientos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTratamientos.setBorderPainted(false);
        btnTratamientos.setContentAreaFilled(false);
        btnTratamientos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTratamientos.setFocusPainted(false);
        btnTratamientos.setVerifyInputWhenFocusTarget(false);
        btnTratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTratamientosActionPerformed(evt);
            }
        });

        salirPr.setBackground(new java.awt.Color(0, 153, 153));
        salirPr.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        salirPr.setForeground(new java.awt.Color(255, 255, 255));
        salirPr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/cancel.png"))); // NOI18N
        salirPr.setText("Cerrar Sesión");
        salirPr.setBorder(new javax.swing.border.MatteBorder(null));
        salirPr.setBorderPainted(false);
        salirPr.setContentAreaFilled(false);
        salirPr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salirPr.setFocusable(false);
        salirPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirPrActionPerformed(evt);
            }
        });

        btnCitas.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnCitas.setForeground(java.awt.SystemColor.control);
        btnCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/calendar (1).png"))); // NOI18N
        btnCitas.setText(" Citas");
        btnCitas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCitas.setBorderPainted(false);
        btnCitas.setContentAreaFilled(false);
        btnCitas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCitas.setFocusPainted(false);
        btnCitas.setVerifyInputWhenFocusTarget(false);
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });

        btnPacientes1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnPacientes1.setForeground(new java.awt.Color(255, 255, 255));
        btnPacientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/teamwork.png"))); // NOI18N
        btnPacientes1.setText("Pacientes");
        btnPacientes1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPacientes1.setBorderPainted(false);
        btnPacientes1.setContentAreaFilled(false);
        btnPacientes1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPacientes1.setFocusPainted(false);
        btnPacientes1.setVerifyInputWhenFocusTarget(false);
        btnPacientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientes1ActionPerformed(evt);
            }
        });

        btnServicios.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnServicios.setForeground(new java.awt.Color(255, 255, 255));
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/drilling.png"))); // NOI18N
        btnServicios.setText("Servicios");
        btnServicios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnServicios.setBorderPainted(false);
        btnServicios.setContentAreaFilled(false);
        btnServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnServicios.setFocusPainted(false);
        btnServicios.setVerifyInputWhenFocusTarget(false);
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });

        btnTratamientos2.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnTratamientos2.setForeground(new java.awt.Color(255, 255, 255));
        btnTratamientos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/diagram.png"))); // NOI18N
        btnTratamientos2.setText("Reportes");
        btnTratamientos2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTratamientos2.setBorderPainted(false);
        btnTratamientos2.setContentAreaFilled(false);
        btnTratamientos2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTratamientos2.setFocusPainted(false);
        btnTratamientos2.setVerifyInputWhenFocusTarget(false);
        btnTratamientos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTratamientos2ActionPerformed(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/user.png"))); // NOI18N

        btnConsultas2.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnConsultas2.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/calendar.png"))); // NOI18N
        btnConsultas2.setText(" Consultas");
        btnConsultas2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultas2.setBorderPainted(false);
        btnConsultas2.setContentAreaFilled(false);
        btnConsultas2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConsultas2.setFocusPainted(false);
        btnConsultas2.setFocusable(false);
        btnConsultas2.setVerifyInputWhenFocusTarget(false);
        btnConsultas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultas2ActionPerformed(evt);
            }
        });

        btnFacebook.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnFacebook.setForeground(new java.awt.Color(255, 255, 255));
        btnFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/facebook.png"))); // NOI18N
        btnFacebook.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFacebook.setBorderPainted(false);
        btnFacebook.setContentAreaFilled(false);
        btnFacebook.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFacebook.setFocusPainted(false);
        btnFacebook.setFocusable(false);
        btnFacebook.setVerifyInputWhenFocusTarget(false);
        btnFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacebookActionPerformed(evt);
            }
        });

        btnInstagram.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnInstagram.setForeground(new java.awt.Color(255, 255, 255));
        btnInstagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/instagram.png"))); // NOI18N
        btnInstagram.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInstagram.setBorderPainted(false);
        btnInstagram.setContentAreaFilled(false);
        btnInstagram.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInstagram.setFocusPainted(false);
        btnInstagram.setFocusable(false);
        btnInstagram.setVerifyInputWhenFocusTarget(false);
        btnInstagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstagramActionPerformed(evt);
            }
        });

        lblNombreConsul.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N
        lblNombreConsul.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreConsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/calendar (1).png"))); // NOI18N

        lblHora.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/clock.png"))); // NOI18N

        lblFecha.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Imagenes/calendar (1).png"))); // NOI18N

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                        .addComponent(btnDoctores, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPacientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTratamientos2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(54, 54, 54))))
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(8, 8, 8)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTratamientos)
                            .addComponent(btnConsultas2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNombreConsul, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salirPr)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(btnFacebook)
                                .addGap(18, 18, 18)
                                .addComponent(btnInstagram, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnCitas)
                        .addGap(28, 28, 28))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelPrincipalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salirPr)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDoctores, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTratamientos))
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnTratamientos2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultas2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnPacientes1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFacebook)
                            .addComponent(btnInstagram, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblNombreConsul, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctoresActionPerformed
         
        new DoctoresP().setVisible(true);
//      
    
    }//GEN-LAST:event_btnDoctoresActionPerformed

    private void btnFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacebookActionPerformed
        // TODO add your handling code here:
   try{
       Desktop.getDesktop().browse(new URI("https://www.facebook.com/CleanDentni/"));
   }
   catch(Exception e){
       JOptionPane.showMessageDialog(null, "Error, no se puede ejecutar la acción");
   }
    
       
    }//GEN-LAST:event_btnFacebookActionPerformed

    private void btnTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTratamientosActionPerformed
          // TODO add your handling code here:
          new Tratamientos().setVisible(true);
      
       
    }//GEN-LAST:event_btnTratamientosActionPerformed

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed
        // TODO add your handling code here:
        new CitasP().setVisible(true);

       
        
    }//GEN-LAST:event_btnCitasActionPerformed

    private void salirPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirPrActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_salirPrActionPerformed

    private void btnPacientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientes1ActionPerformed
      new PacientesP().setVisible(true);
      
        
    }//GEN-LAST:event_btnPacientes1ActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        // TODO add your handling code here:
        new Servicios().setVisible(true);
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnTratamientos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTratamientos2ActionPerformed
new  Reportes().setVisible(true);
    }//GEN-LAST:event_btnTratamientos2ActionPerformed

    private void btnConsultas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultas2ActionPerformed

    private void btnInstagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstagramActionPerformed
        
        
       
        try{
       Desktop.getDesktop().browse(new URI("https://www.instagram.com/p/B1ZKH92ByqB/"));
   }
   catch(Exception e){
       JOptionPane.showMessageDialog(null, "Error, no se puede ejecutar la acción");
   }
    }//GEN-LAST:event_btnInstagramActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnConsultas2;
    private javax.swing.JButton btnDoctores;
    private javax.swing.JButton btnFacebook;
    private javax.swing.JButton btnInstagram;
    private javax.swing.JButton btnPacientes1;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnTratamientos;
    private javax.swing.JButton btnTratamientos2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNombreConsul;
    private javax.swing.JLabel lblUser;
    private javax.swing.JButton salirPr;
    // End of variables declaration//GEN-END:variables

//public void FechaHoraSistema(){
//    Calendar cal = Calendar.getInstance();
//    String fecha, hora;
//    fecha = cal.get(Calendar.DATE)+"/"+cal.get(Calendar.MONTH)+"/"+cal.get(Calendar.YEAR);
//    hora = cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+":"+cal.get(Calendar.SECOND);
//    
//}

}



